version: '3.3'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - /mnt/frontend:/usr/share/nginx/html
    depends_on:
      - api
      - mariadb
  api:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - /mnt/api/node_test:/usr/src/app
    command: sh -c "npm install && npm run start"
    ports:
      - "5000:5555"  # เปิด port สำหรับ API
    environment:
      - NODE_ENV=development  # ตั้งค่า environment ให้เหมาะสม
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: buopen@am1n2024
      MYSQL_DATABASE: oph
      MYSQL_USER: oph
      MYSQL_PASSWORD: buopen@am1n2024
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: buopen@am1n2024
    depends_on:
      - mariadb
volumes:
  mariadb_data:

networks:
  default:
    external:
      name: oph_network